---
title: "General lab expectations"
author: "Jenny Gremer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Gremer lab expectations 

Welcome to the Gremer lab!  Our lab members are committed to doing strong, reproducible, ethical scientific research and are committed to creating, maintaining, and promoting a safe and inclusive community of research and inquiry.  We expect all members of the lab to establish and cultivate an environment that is conducive to learning, curiosity, and collegiality.  This statement provides more information on how we go about achieving those goals.  

## General Conduct ## 

All members of the lab are expected to treat each other with respect and kindness.  In our lab, curiosity and engagement are encouraged, regardless of background.  Lab members are expected to be open to new perspectives and ideas as well as share them.  There are no ‘dumb questions’ and we strive to create a community where sharing ideas, thoughts, and perspectives is not only safe, but welcomed and encouraged.  Feedback is expected to be respectful and constructive.  Insults, offensive language, disrespect, or harassment of any kind are not acceptable and will not be tolerated. 
 
The Gremer lab is deeply committed to recruiting, training, and promoting scholars of diverse backgrounds.   We recognize that, much like the value of diversity in ecological function, diversity in perspectives and backgrounds makes our community and our science stronger.  It also creates an environment in which creativity and innovation thrive.  We do not tolerate discrimination in regard to race, ethnicity, socioeconomic status, (dis)ability, sexuality, gender, religious or spiritual beliefs, or other axes of identity.  Further, we cultivate a community of allyship and education.  We are actively involved in advancing our understanding, approaches, and tools for improving justice, equity, diversity and inclusion in our lab community, as well as the rest of our academic, professional, and personal lives.  Members are encouraged to speak out against discriminatory words or practices and work against them.  

We also recognize that in order to do excellent science, we need to take care of ourselves as scientists.  We expect members to be wholly present in the lab when they are there and encourage balancing academic and professional responsibilities with personal lives and goals.  In other words, we respect and encourage finding work-life balance.  We expect members to manage their time effectively and to discuss schedules and work-life balance with their advisor and/or supervisor and we encourage discussion and sharing of resources about achieving this balance.  Managing physical, mental, and emotional health is also critical for us as scientists, humans, and community members.  Please be proactive about self-care and let us know if you need additional resources or assistance with doing so.  

Finally, behave in a manner in shared spaces that maintains a safe, respectful, and pleasant space.  Ask each other which pronouns to use.  Stay home if you are not feeling well.  Be courteous to others in shared spaces by not being disruptive and cleaning up after yourself.  Respect personal space and comfort.  Secure space and belongings by keeping doors locked when others aren’t around, caring for equipment, and returning items to their original locations after use.       

### Communication
We are committed to clear, open communication that is based on trust and mutual respect.  We also promote the exchange of information, ideas, and resources.  Communication is expected to be guided by the principles of conduct outlined above.  In addition to those guidelines, here are ways we expect communication to proceed:

-	Digital communication should be conducted primarily over Slack.  Please post communication to the relevant Slack channel if appropriate, since that keeps messages organized by project or topic.  If that is not appropriate use the direct messaging function in Slack.
-	Use email if that is more appropriate, such as when it includes members outside of our group or for formal reasons.  
-	Respond to communication in a timely manner and let us know when you will be unable to do so.  In addition to communicating with other lab members directly, especially advisor(s) and/or supervisor(s), please use the Gremer lab availability calendar to indicate times when you will be unavailable or out of contact.
-	Recognize and respect that lab members may have different working and communication schedules.  Please feel free to send messages on your own schedule but recognize that responses may align with others’ schedules (and the two may be different). 
-	If there are urgent matters, please contact the relevant lab member directly by phone as needed.  

### Safety
We expect research and activities to comply with safe, ethical practices and protocols including compliance with lab, campus, regional, and federal safety guidelines.  Complete safety trainings promptly and conscientiously, refresh and revise protocols regularly as needed, and communicate any concerns or questions to your supervisor or advisor.  See lab safety resources for specifics.  

### Participation
We strive to be a collaborative, interactive lab community.  We expect members to be active participants in our lab, campus, and broader scientific communities and encourage the sharing and discussion of ideas, expertise, guidance, and help.  In our lab, we help each other out when needed and pay it forward- there may be times when you need help, and other times when you can contribute to a group effort.  Be willing to pull together to help our community.   

_Lab meetings_:

-	Graduate students and postdocs are expected to participate in lab meetings and lead/organize one lab meeting per term (or more).
-	Undergraduates are encouraged to come to lab meeting whenever possible, though we recognize that course schedules may interfere with attendance.  
-	Come prepared to lab meeting ready to discuss ideas, give feedback, or participate in activities.
-	If you are leading lab meeting, provide materials to read or other information on activities with enough lead time that folks can arrive prepared and ready to participate.  

_Seminars_:

-	Graduate students and postdocs are expected to attend seminars, at least 1-2 per week.  Our group typically attends the Center for Population Biology and the Ecology & Evolution seminars, but there are many seminar series to choose from.  
-	Go to seminars even if the title or topic is not directly related to your particular project or field of study.  We attend seminars to learn new ideas, broaden our understanding, and get inspiration, among other benefits.  You may be surprised by what you can gain by attending a diversity of seminars.  
-	Meet with seminar speakers whenever possible.  This is a great way to network, get feedback, learn, and get new ideas.  Meet with seminar speakers individually, or with others or in a group to facilitate comfort and discussion.  

_Social events_: 

While not required, we encourage members to join us for social lab functions like potlucks, craft nights, or other events.  These events give us an opportunity to get to know each other in addition to our science and promote team work and community.  We expect behavior at these events to follow the conduct guidelines above- be present, kind, respectful, and engaged.  

### Authorship and contributions
Authorship contributions will be assessed based on contributions to the following key components of a scientific study:
1.	Conception, development, and design of the study
2.	Participation in the execution of the study
3.	Data analysis and interpretation
4.	Writing the manuscript describing the study

Generally, an author or coauthor is expected to have significant contributions in at least two to three of these areas.  Our expectation is that author contributions be discussed early and often in project development, execution, and publication.  If an individual’s knowledge, expertise, experiment or system, or data is used for a study, it is our practice to offer and discuss authorship contributions to that individual in early stages of project development and communicate with that individual as the project progresses.  

We strive to be inclusive in our authorship guidelines, which follow those put forward by the Ecological Society of America and are fairly standard in the field.  However, we recognize that historically underrepresented or marginalized groups have not always received recognition of their contributions.  Please keep this in mind when considering authorship contributions and make sure to consider and acknowledge contributions from all team members that meet the criteria above.  When undergraduates are involved in the project, please discuss contributions early and often and extend involvement beyond graduation when possible and appropriate.  Lead authors are responsible for keeping contributors and collaborators apprised of progress and activities and included in development, implementation, and publication of studies.  

All authors are responsible for having read, understood, and approved manuscripts for publication.  

### Data management
Data protection and management is key to our goal of doing rigorous, defensible, and reproducible science.  Each member of the lab is responsible for the data they collect, including documentation of how data was collected, analyzed, stored, and published.  

Generally, files should be stored on Box and your own hard drive/external drive for longer term storage.  Google Drive, docs, and sheets can be used for “living” documents that are being edited, updated, or added to, but finalized versions of any files should be stored on the Gremer Lab Box drive.  If there are documents regularly updated on Google drive (e.g. the lab seed inventory list), they should be regularly downloaded and backed up on Box.  Google Drive is NOT long-term storage.  Back up files to either a hard drive or external drive regularly, in addition to storing it on Box.  

Our data management protocol includes:

- Documenting data collection methods using protocols, README files, and lab or field notebooks, as well as photo documentation of experimental set up, activities, and samples. 
- Protocols should be stored on the Gremer lab Box drive in the protocols folder or in the relevant project folder.  
     - Protocols should include enough detail to completely reproduce your methods.  
     -	Draft protocols can be stored on the shared lab Google drive, but once finalized must be stored on Box.  
     -	Dates of creation and revision of protocols should be explicitly stated in the protocol document. 
-	Hand-written or hard copies of data should be scanned promptly and organized into a ‘scanned data’ folder on Box within the relevant project folder. 
      -	After scanning, hard copies should be stored in lab file cabinets, labeled with the project, year, and name(s) of project leaders.  
-	Samples or specimens should be stored appropriately in the lab (or freezer) and clearly labeled with your name, the project, the date, and a brief description of contents (e.g. “seeds” or “biomass”).  
-	Photos should be stored in a “photos” folder in the relevant Box folder.
-	Entered data is to be stored in a “Raw Data” folder on the Gremer Lab Box Drive within the relevant project folder and stored as a .csv file along with the README file for those data.  
-	Do NOT store data without a README.  
    -	README text files must include key details and information about the data should be stored alongside data files on Box.  These include: 
          -	Why were the data collected?  As part of what project?
          - Who collected and entered the data?
          -	When were the data collected?  Where?
          -	What does each column mean?  What units are the data in?
          -	Definitions of any abbreviations or terms
-	Any data checking, cleaning, or formatting should be done in R, with a script documenting EVERYTHING done to the data.  This should be done using version control.  Store cleaning and formatting scripts in the workflow in the relevant GitHub repository. If you don’t use GitHub (and you should) make sure cleaning and formatting scripts are stored with the data.  
-	Final data analyses scripts should be organized and carefully commented.  Graduate students, postdocs, and technicians are expected to use GitHub to compile and share scripts, including cleaning and formatting scripts.  
-	Data and associated scripts for analyses should be made public immediately at the time of publication or within two years of completion of the project.  

### Departing the lab
The nature of our community is that folks, besides Jenny, will eventually move on.  When that time comes, we ask you to:
-	Provide clear communication about your departure schedule and coordinate meeting with Jenny or your advisor/supervisor before you go.
-	Provide clear documentation of your data, analyses, and samples.  Follow the guidelines above in data management. 
-	Upload any presentations, posters, or manuscripts (or theses) related to your work on the Gremer lab Box drive in the appropriate folder.  
-	Turn in your keys to the EVE office and/or any other offices (e.g. Plant Biology) and let Jenny know that you did so.  
-	Provide your contact information.  
-	Keep in touch!  One of our (Jenny’s at least) favorite things is to hear what folks are up to after they leave thelab. We encourage you to keep in touch about ongoing projects as well.  
